spring.application.name=SUPPORT-SERVICE

server.port = 8083
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory-management-db
spring.datasource.username=postgres
spring.datasource.password=driThy

#add actuators
management.endpoints.web.exposure.include=*

# Connection Pool (HikariCP - default in Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Optional Logging (helps during debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# discovery client
eureka.client.service-url.defaultZone = http://localhost:8761/eureka