spring.application.name=support-service

server.port = 8083
spring.datasource.url=${ORDER_DB_URL}
spring.datasource.username=${ORDER_DB_USERNAME}
spring.datasource.password=${ORDER_DB_PASSWORD}

# Connection Pool (HikariCP - default in Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Optional Logging (helps during debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE